/**
 * Token emitters — turn the source tokens (tokens.ts) into the artifacts each
 * surface consumes: a Tailwind v4 `@theme` stylesheet (launcher), JSON
 * (tooling), and Kotlin (Lumen / the mod).
 *
 * Every emitter derives from the same `tokens` object, so the launcher and the
 * in-game UI cannot drift (DESIGN_SPEC §5).
 */

import { color, radius, motion, typography } from "./tokens.js";

/** Flatten a nested string map into dash-joined leaf entries. */
function flatten(
  obj: Record<string, unknown>,
  prefix: string[] = [],
): Array<[string, string]> {
  const out: Array<[string, string]> = [];
  for (const [key, value] of Object.entries(obj)) {
    const path = [...prefix, key];
    if (value && typeof value === "object") {
      out.push(...flatten(value as Record<string, unknown>, path));
    } else {
      out.push([path.join("-"), String(value)]);
    }
  }
  return out;
}

const CSS_HEADER = `/* GENERATED by @orrery/design-tokens — do not edit by hand.
   Source: packages/design-tokens/src/tokens.ts */`;

/** All color tokens flattened to `name -> #hex`, e.g. `void-base`, `rarity-epic`. */
export function colorEntries(): Array<[string, string]> {
  return flatten(color);
}

/**
 * Tailwind v4 `@theme` stylesheet for the launcher. The variables both
 * generate utilities (`bg-void-base`, `text-h1`, `rounded-lg`, `font-display`,
 * `ease-instrument`) and are exposed as `:root` custom properties for use
 * anywhere. Consume after `@import "tailwindcss";`. Tailwind v4 is CSS-first —
 * there is no JS config/preset (DESIGN_SPEC §5; launcher uses Tailwind v4).
 */
export function emitCss(): string {
  const lines: string[] = [CSS_HEADER, ``, `@theme {`];

  lines.push(`  /* color */`);
  for (const [name, hex] of colorEntries()) {
    lines.push(`  --color-${name}: ${hex};`);
  }

  lines.push(``, `  /* radius */`);
  for (const [name, value] of Object.entries(radius)) {
    lines.push(`  --radius-${name}: ${value}px;`);
  }

  lines.push(``, `  /* type */`);
  for (const [role, family] of Object.entries(typography.family)) {
    const fallback = role === "mono" ? "monospace" : "sans-serif";
    lines.push(`  --font-${role}: "${family}", ${fallback};`);
  }
  for (const [name, px] of Object.entries(typography.scale)) {
    lines.push(`  --text-${name}: ${px}px;`);
  }

  lines.push(``, `  /* motion */`);
  lines.push(`  --ease-instrument: ${motion.easing};`);
  lines.push(`  --duration-fast: ${motion.fast}ms;`);
  lines.push(`  --duration-base: ${motion.base}ms;`);
  lines.push(`  --duration-slow: ${motion.slow}ms;`);

  lines.push(`}`, ``);
  return lines.join("\n");
}

/** Stable JSON snapshot of every token (tooling / drift checks). */
export function emitJson(): string {
  return JSON.stringify({ color, radius, motion, typography }, null, 2) + "\n";
}

/** `#RRGGBB` -> Kotlin ARGB int literal `0xFFRRGGBB.toInt()`. */
function hexToKotlinArgb(hex: string): string {
  const rgb = hex.replace("#", "").toUpperCase();
  return `0xFF${rgb}.toInt()`;
}

/** Convert a flattened token name (`void-base`) to camelCase (`voidBase`). */
function camel(name: string): string {
  return name.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}

/**
 * Kotlin `Tokens` object for Lumen. Colors as ARGB ints, radius/motion as
 * Int constants. Lumen renders ONLY from this — no hardcoded colors (§5, §11).
 */
export function emitKotlin(pkg = "gg.orrery.generated"): string {
  const colorConsts = colorEntries()
    .map(([name, hex]) => `    val ${camel(name)} = ${hexToKotlinArgb(hex)}`)
    .join("\n");

  const radiusConsts = Object.entries(radius)
    .map(([name, v]) => `    const val ${name} = ${v}`)
    .join("\n");

  const motionConsts = Object.entries(motion)
    .filter(([name]) => name !== "easing")
    .map(([name, v]) => `    const val ${name} = ${v}`)
    .join("\n");

  const scaleConsts = Object.entries(typography.scale)
    .map(([name, v]) => `    const val ${name} = ${v}`)
    .join("\n");

  const families = Object.entries(typography.family)
    .map(([role, fam]) => `    const val ${role} = ${JSON.stringify(fam)}`)
    .join("\n");

  return `// GENERATED by @orrery/design-tokens — do not edit by hand.
// Source: packages/design-tokens/src/tokens.ts
package ${pkg}

/**
 * Orrery design tokens (DESIGN_SPEC §5). Lumen renders ONLY from this object:
 * no hardcoded colors, no Minecraft fonts, no vanilla chrome (§5.1, §11).
 * Colors are ARGB ints (0xAARRGGBB).
 */
object Tokens {
  object Color {
${colorConsts}
  }

  object Radius {
${radiusConsts}
  }

  /** Durations in milliseconds. */
  object Motion {
${motionConsts}
  }

  /** Type scale in px. */
  object TextScale {
${scaleConsts}
  }

  object Font {
${families}
  }
}
`;
}
